### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by whit2333** [jart/hiptext#14]
$ make
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o hiptext.o hiptext.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o artiste.o artiste.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o charquantizer.o charquantizer.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD -I/usr/include/freetype2  -march=native -c -o font.o font.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o graphic.o graphic.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o jpeg.o jpeg.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o macterm.o macterm.cc
g++ -g -O3 -std=c++11 -Wall -Wextra -Werror -fno-exceptions -fno-rtti -MD  -march=native -c -o movie.o movie.cc
movie.cc: In destructor ‘Movie::~Movie()’:
movie.cc:42:48: error: ‘avformat_close_input’ was not declared in this scope
   if (format_)    avformat_close_input(&format_);
                                                ^
make: *** [movie.o] Error 1

**Comment by jart** [comment]
Would you guys mind taking another look? Everything builds fine for me on:

    master jart@gothpad:~/hiptext$ g++ --version
    g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

And:

    master jart@gothpad:~/hiptext$ $CXX --version
    Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

**Comment by whit2333** [comment]
Just tried to build on my new machine. Works fine! Nice job.

**Comment by jart** [comment]
Hooray!
