### ISSUE TITLE
~Artiste() is missing

### ISSUE THREAD

**Issue by yurivict** [jart/hiptext#33]
You need this:
```
-  ~Artiste();
+  ~Artiste() { }
```

**Comment by jart** [comment]
Is something giving you a compile error? Shouldn't we be able to just remove that destructor definition entirely?

**Comment by yurivict** [comment]
Gave me a compiler error. Should be possible to remove.

**Comment by jart** [comment]
What compiler were you using?

**Comment by yurivict** [comment]
clang
