### ISSUE TITLE
could not find  ft2build.h

### ISSUE THREAD

**Issue by laoshaw** [jart/hiptext#37]
On ubuntu 16.04 x86 I got : 
src/font.cc:6:22: fatal error: ft2build.h: No such file or directory

I manually added -I /usr/include/freetype2 to get it compiled, something configure script did not get the include path right.

**Comment by jart** [comment]
I'll be upgrading to Ubuntu 16.04 at home in the next week or so. Until then I probably can't fix this. But patches welcome.

**Comment by laoshaw** [comment]
Just did some debugging, freetype2-config is using my android header files as I set SYSROOT in my .bashrc. After unset that everything is good. This is not a bug per se.
