### ISSUE TITLE
Missing libgflags.pc on ubuntu 1604

### ISSUE THREAD

**Issue by laoshaw** [jart/hiptext#38]
To build this on ubuntu 1604 the configure will fail to find libgflags.pc which was missing from ubuntu. I added it manually to /usr/lib/x86_64-linux-gnu/pkgconfig/libgflags.pc with content like:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: gflags
Version: 2.0
Description: A commandline flags library that allows for distributed flags
URL: http://code.google.com/p/gflags
Requires:
Libs: -L${libdir} -lgflags
Libs.private: -pthread -lpthread
Cflags: -I${includedir}`
```

**Comment by jart** [comment]
@laoshaw can you please pull and confirm if the problem is fixed?

**Comment by laoshaw** [comment]
tested and it's fixed .Thanks.
