### ISSUE TITLE
Makefile refers to src/pixel_parse.cc that doesn't exist

### ISSUE THREAD

**Issue by yurivict** [jart/hiptext#47]
src/pixel_parse.cc

**Comment by jart** [comment]
Behold! Our [wildcard rule](https://github.com/jart/hiptext/blob/a8755090650ebaf62f80a9e72e0285d1b6df0cb8/Makefile.am#L120) for Ragel.

```make
src/%.cc: src/%.rl
	@echo "  RL      " $@;
	$(RAGEL) -G2 -o $@ $<
```

I'm proud to say I'm also a contributor to the Ragel project. Although I've sometimes wondered if it's leaky abstraction and we're better off just writing our state machines by hand using switch statements.
