### ISSUE TITLE
Where is pixel_parser.cc?

### ISSUE THREAD

**Issue by fCorleone** [jart/hiptext#51]
When I use make -j4 to compile the program , a source code called 'pixel_parser.cc' has missed. I wonder where could I find this file, or wasI just did something wrong ?

**Comment by jart** [comment]
You need [Ragel](http://www.colm.net/open-source/ragel/) to turn https://github.com/jart/hiptext/blob/master/src/pixel_parse.rl into a .cc file. Try `sudo apt-get install ragel`.

**Comment by fCorleone** [comment]
Thank you for that.
