### ISSUE TITLE
configure error when using brew installed gflags

### ISSUE THREAD

**Issue by WindProphet** [jart/hiptext#54]
When compile it using gflags installed by HomeBrew
It occur a problem that `libgflags` cannot be founded.

set the environment to this to avoid this problem.

```
env LIBGFLAGS_LIBS=`pkg-config --libs gflags` LIBGFLAGS_CFLAGS=`pkg-config --cflags gflags` ./configure
```

**Comment by imbible** [comment]
It shows
`env: -lgflags: No such file or directory`.

`pkg-config --libs gflags`
returns
`-L/usr/local/Cellar/gflags/2.2.2/lib -lgflags`
